# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botbox < Formula
  desc "Your botbox description here"
  homepage "https://github.com/choice404/botbox"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choice404/botbox/releases/download/v2.0.1/botbox_Darwin_x86_64.tar.gz"
      sha256 "ae68f78babfbfabb79ba13c065399a1a3725be5cae1bfbe160a6b7c59d1c26f2"

      def install
        bin.install "botbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choice404/botbox/releases/download/v2.0.1/botbox_Darwin_arm64.tar.gz"
      sha256 "1aada190f724e52a9c47fe1aff7a122b5e2fe6aa77b7e726e55b6ea855d34549"

      def install
        bin.install "botbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choice404/botbox/releases/download/v2.0.1/botbox_Linux_x86_64.tar.gz"
        sha256 "9f479474a40726d0493c144e92c3e1058df6b851e2745660a8a48c4c4e769aa8"

        def install
          bin.install "botbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choice404/botbox/releases/download/v2.0.1/botbox_Linux_arm64.tar.gz"
        sha256 "498497058da5abae38922810111feb222917da5709169c76032c2d1f731ad881"

        def install
          bin.install "botbox"
        end
      end
    end
  end

  test do
    system "#{bin}/botbox --version"
  end
end
