# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botbox < Formula
  desc "Your botbox description here"
  homepage "https://github.com/choice404/botbox"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choice404/botbox/releases/download/v2.0.2/botbox_Darwin_x86_64.tar.gz"
      sha256 "70b7a09ee4ec4ceb41e20e94fca23a25ed1e6db186f1769e278af778eb5e6ff6"

      def install
        bin.install "botbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choice404/botbox/releases/download/v2.0.2/botbox_Darwin_arm64.tar.gz"
      sha256 "a30bc78f40ff3b2e9addc5eb6445aae9acac12a49dfa07de5be5296f677eec31"

      def install
        bin.install "botbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choice404/botbox/releases/download/v2.0.2/botbox_Linux_x86_64.tar.gz"
        sha256 "3986eba5b6d6c5541fc2034ca5031eae882d62f3ad7b1fa961ffec4475f1cee2"

        def install
          bin.install "botbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choice404/botbox/releases/download/v2.0.2/botbox_Linux_arm64.tar.gz"
        sha256 "b1dc94a258e9123a97507afdd6819593fba90244df515281fb8c21d48344a1e7"

        def install
          bin.install "botbox"
        end
      end
    end
  end

  test do
    system "#{bin}/botbox --version"
  end
end
