"""
Bot Author: Austin Choi

TestBot
A discord bot used by the parser tests
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("DISCORD_GUILD", 0))
GUILD = discord.Object(id=GUILD_ID)

class AdminCog(commands.Cog):
    def __init__(self, bot) -> None:
        self.bot = bot

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        return await self.bot.is_owner(interaction.user)

    @app_commands.command(name="sync", description="Syncs slash commands with Discord")
    @app_commands.guilds(GUILD)
    @app_commands.default_permissions(administrator=True)
    @app_commands.describe(scope="Where to sync commands: guild or global")
    @app_commands.choices(scope=[
        app_commands.Choice(name="guild", value="guild"),
        app_commands.Choice(name="global", value="global"),
    ])
    async def sync(self, interaction: discord.Interaction, scope: str) -> None:
        """
        Forces a slash command sync and reports how many commands were synced.

            Parameters:
                interaction (discord.Interaction): The interaction object that triggered the command
                scope (str): Where to sync commands, guild or global

            Returns:
                None
        """

        await interaction.response.send_message(f"synced {scope}", ephemeral=True)

    @app_commands.command(name="uptime", description="Shows how long the bot has been online")
    @app_commands.guilds(GUILD)
    @app_commands.default_permissions(administrator=True)
    async def uptime(self, interaction: discord.Interaction) -> None:
        """
        Shows the elapsed time since the bot started.

            Parameters:
                interaction (discord.Interaction): The interaction object that triggered the command

            Returns:
                None
        """

        await interaction.response.send_message("0d 0h 0m 0s", ephemeral=True)

async def setup(bot):
    await bot.add_cog(AdminCog(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""
