"""
Bot Author: Austin Choi

TestBot
A discord bot used by the parser tests
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("DISCORD_GUILD", 0))
GUILD = discord.Object(id=GUILD_ID)

class HelpView(discord.ui.View):
    def __init__(self, pages: list) -> None:
        super().__init__(timeout=120)
        self.pages = pages
        self.index = 0

    @discord.ui.button(label='Previous', style=discord.ButtonStyle.secondary)
    async def previous_page(self, interaction: discord.Interaction, button: discord.ui.Button) -> None:
        self.index -= 1

    @discord.ui.button(label='Next', style=discord.ButtonStyle.secondary)
    async def next_page(self, interaction: discord.Interaction, button: discord.ui.Button) -> None:
        self.index += 1

class HelpCog(commands.Cog):
    def __init__(self, bot) -> None:
        self.bot = bot

    @app_commands.command(name="help", description="Shows all bot commands")
    @app_commands.guilds(GUILD)
    async def help(self, interaction: discord.Interaction) -> None:
        """
        Shows the commands the user is allowed to run, one page per cog.

            Parameters:
                interaction (discord.Interaction): The interaction object that triggered the command

            Returns:
                None
        """

        await interaction.response.send_message("help", ephemeral=True)

async def setup(bot):
    await bot.add_cog(HelpCog(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""
