"""
Bot Author: Austin Choi

TestBot
A discord bot used by the parser tests
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("DISCORD_GUILD", 0))
GUILD = discord.Object(id=GUILD_ID)

class FeedbackModal(discord.ui.Modal, title="Collects feedback from a member"):
    summary = discord.ui.TextInput(label="Feedback summary", style=discord.TextStyle.short, required=True, placeholder="Short summary")
    details = discord.ui.TextInput(label="Feedback details", style=discord.TextStyle.paragraph, required=False)

    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.send_message(f"feedback submitted: summary={self.summary.value} details={self.details.value}", ephemeral=True)

class ModalCog(commands.Cog, name="ModalCog"):
    def __init__(self, bot) -> None:
        self.bot = bot
        print("modalCog cog loaded")

    @app_commands.command(name="feedback", description="Collects feedback from a member")
    @app_commands.guilds(GUILD)
    async def feedback(self, interaction: discord.Interaction) -> None:
        """
        Collects feedback from a member when the user types "/feedback"

            Returns:
                    None
        """

        await interaction.response.send_modal(FeedbackModal())

async def setup(bot):
    await bot.add_cog(ModalCog(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""
