"""
Bot Author: Austin Choi

TestBot
A discord bot used by the parser tests
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

try:
    from utils.logger import get_logger
    logger = get_logger(__name__)
except ImportError:
    import logging
    logger = logging.getLogger(__name__)

load_dotenv()

GUILD_ID = int(os.getenv("DISCORD_GUILD", 0))
GUILD = discord.Object(id=GUILD_ID)

class ResponseCog(commands.Cog, name="ResponseCog"):
    def __init__(self, bot) -> None:
        self.bot = bot
        logger.info("ResponseCog cog loaded")

    @app_commands.command(name="greet", description="Greets a member")
    @app_commands.describe(
        member="Who to greet",
    )
    async def greet(self, interaction: discord.Interaction, member: str) -> None:
        """
        Greets a member when the user types "/greet"

            Parameters:
                    member (str): Who to greet

            Returns:
                    None
        """

        try:
            await interaction.response.send_message(f"Hello {member}", ephemeral=False)
        except Exception as e:
            logger.error(f"Error: {e}")
            await interaction.response.send_message(f"Error: {e}", ephemeral=True)

        return None

    @commands.command()
    async def ping(self, ctx: commands.Context, count: int) -> None:
        """
        Replies with pong when the user types "/ping"

            Parameters:

                    count (int): How many pings

            Returns:
                    None
        """

        try:
            await ctx.send(f"ping", ephemeral=True)
        except Exception as e:
            logger.error(f"Error: {e}")
            await ctx.send(f"Error: {e}", ephemeral=True)

        return None


async def setup(bot):
    await bot.add_cog(ResponseCog(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""