"""
Bot Author: Austin Choi

TestBot
A discord bot used by the parser tests
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("DISCORD_GUILD", 0))
GUILD = discord.Object(id=GUILD_ID)

class ValidCog(commands.Cog, name="ValidCog"):
    def __init__(self, bot) -> None:
        self.bot = bot
        print("validCog cog loaded")

    @app_commands.command(name="greet", description="Greets a member")
    @app_commands.describe(
        member="The member to greet",
        times="How many times to greet",
    )
    @app_commands.guilds(GUILD)
    async def greet(self, interaction: discord.Interaction, member: discord.Member, times: int) -> str:
        """
        Greets a member when the user types "/greet"

            Parameters:
                    member (discord.Member): The member to greet
                    times (int): How many times to greet

            Returns:
                    str
        """

        try:
            await interaction.response.send_message(f"greet", ephemeral=True)
        except Exception as e:
            print(f"Error: {e}")
            await interaction.response.send_message(f"Error: {e}", ephemeral=True)

        return ""

    @commands.command()
    async def ping(self, ctx: commands.Context, count: int) -> None:
        """
        Replies with pong when the user types "/ping"

            Parameters:
                    count (int): How many pongs to send

            Returns:
                    None
        """

        try:
            await ctx.send(f"ping")
        except Exception as e:
            print(f"Error: {e}")

        return None

async def setup(bot):
    await bot.add_cog(ValidCog(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""
