#!/bin/bash
# This script will run the bot
# Make sure to give it execute permissions with chmod +x run.sh
# and run it with ./run.sh
# If you are using botbox to run your bot, you can run it with the command: botbox run

python3 src/main.py

# Script generated by BotBox - https://github.com/choice404/botbox