"""
Bot Author: tester

test
testing
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("GUILD_ID", 0))
GUILD = discord.Object(id=GUILD_ID) if GUILD_ID else None

class Test(commands.Cog, name="Test"):
    def __init__(self, bot) -> None:
        self.bot = bot
        print("test cog loaded")

    @app_commands.command(name="asfd", description="asdf")
    @app_commands.describe(
        asdf="asdf",
    )
    @app_commands.guilds(GUILD) if GUILD else app_commands.default_permissions
    async def asfd(self, interaction: discord.Interaction, asdf: str) -> str:
        """
        asdf when the user types "/asfd"

            Parameters:
                    asdf (str): asdf

            Returns:
                    str
        """

        try:
            await interaction.response.send_message(f"asfd", ephemeral=True)
        except Exception as e:
            print(f"Error: {e}")
            await interaction.response.send_message(f"Error: {e}", ephemeral=True)

        return ""

    @commands.command()
    async def fdsa(self, ctx: commands.Context, fdsa: float) -> str:
        """
        fdsa when the user types "/fdsa"

            Parameters:

                    fdsa (float): fdsa

            Returns:
                    str
        """

        try:
            await ctx.send(f"fdsa", ephemeral=True)
        except Exception as e:
            print(f"Error: {e}")
            await ctx.send(f"Error: {e}", ephemeral=True)

        return ""


async def setup(bot):
    await bot.add_cog(Test(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""