/*
Copyright © 2025 Austin Choi austinch20@protonmail.com
See end of file for extended copyright information
*/

package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/choice404/botbox/v2/cmd/utils"
	"github.com/spf13/cobra"
)

var ()

var addCmd = &cobra.Command{
	Use:   "add",
	Short: "Adds new cog to the project",
	Long: `This command allows you to add a new cog to your bot project.
You can specify the cog structure as well as create commands for the cog.
`,
	Run: func(cmd *cobra.Command, args []string) {
		_, err := utils.FindBotConf()
		if err != nil {
			fmt.Println("Current directory is not in a botbox project.")
			return
		}

		model := utils.AddModel(addCallback)
		utils.CupSleeve(&model)
	},
}

func addCallback(values map[string]string) {
	rootDir, err := utils.FindBotConf()
	config, err := utils.LoadConfig()
	if err != nil {
		fmt.Println("Error loading config:", err)
		return
	}

	filename := values["filename"]
	slashCommandList, _ := utils.JSONToCmdInfoSlice(values["slashCommands"])
	prefixCommandList, _ := utils.JSONToCmdInfoSlice(values["prefixCommands"])

	filePath := filepath.Join(rootDir, "src", "cogs", filename+".py")
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer file.Close()

	className := strings.ToUpper(string(filename[0])) + filename[1:]

	var cogContent strings.Builder

	fmt.Fprintf(&cogContent, `"""
Bot Author: %s

%s
%s
"""

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv
import os

load_dotenv()

GUILD_ID = int(os.getenv("GUILD_ID", 0))
GUILD = discord.Object(id=GUILD_ID) if GUILD_ID else None

class %s(commands.Cog, name="%s"):
    def __init__(self, bot) -> None:
        self.bot = bot
        print("%s cog loaded")
`, config.BotInfo.Author, config.BotInfo.Name, config.BotInfo.Description, className, className, filename)

	for _, command := range slashCommandList {
		fullArgStr := buildArgString(command.Args)

		fmt.Fprintf(&cogContent, `
    @app_commands.command(name="%s", description="%s")`, command.Name, command.Description)

		if fullArgStr != "" {
			cogContent.WriteString(`
    @app_commands.describe(`)

			for _, arg := range command.Args {
				fmt.Fprintf(&cogContent, `
        %s="%s",`, arg.Name, arg.Description)
			}

			fmt.Fprintf(&cogContent, `
    )`)
		}

		if command.Scope == "guild" {
			fmt.Fprintf(&cogContent, `
    @app_commands.guilds(GUILD) if GUILD else app_commands.default_permissions`)
		}

		fmt.Fprintf(&cogContent, `
    async def %s(self, interaction: discord.Interaction, %s) -> %s:
        """
        %s when the user types "/%s"

            Parameters:`, command.Name, fullArgStr, command.ReturnType, command.Description, command.Name)

		for _, arg := range command.Args {
			fmt.Fprintf(&cogContent, `
                    %s (%s): %s`, arg.Name, arg.Type, arg.Description)
		}

		fmt.Fprintf(&cogContent, `

            Returns:
                    %s
        """

        try:
            await interaction.response.send_message(f"%s", ephemeral=True)
        except Exception as e:
            print(f"Error: {e}")
            await interaction.response.send_message(f"Error: {e}", ephemeral=True)

        return %s
`, command.ReturnType, command.Name, getReturnValue(command.ReturnType))
	}

	for _, command := range prefixCommandList {
		fullArgStr := buildArgString(command.Args)

		fmt.Fprintf(&cogContent, `
    @commands.command()
    async def %s(self, ctx: commands.Context, %s) -> %s:
        """
        %s when the user types "/%s"

            Parameters:
`, command.Name, fullArgStr, command.ReturnType, command.Description, command.Name)

		for _, arg := range command.Args {
			fmt.Fprintf(&cogContent, `
                    %s (%s): %s`, arg.Name, arg.Type, arg.Description)
		}

		fmt.Fprintf(&cogContent, `

            Returns:
                    %s
        """

        try:
            await ctx.send(f"%s", ephemeral=True)
        except Exception as e:
            print(f"Error: {e}")
            await ctx.send(f"Error: {e}", ephemeral=True)

        return %s
`, command.ReturnType, command.Name, getReturnValue(command.ReturnType))
	}

	fmt.Fprintf(&cogContent, `

async def setup(bot):
    await bot.add_cog(%s(bot))

"""
File generated by BotBox - https://github.com/choice404/botbox
"""`, className)

	_, err = file.WriteString(cogContent.String())
	if err != nil {
		fmt.Println("Error writing to file:", err)
		return
	}

	err = file.Sync()
	if err != nil {
		fmt.Println("Error syncing file:", err)
		return
	}

	cog := utils.CogConfig{
		Name:           strings.ToUpper(string(filename[0])) + filename[1:],
		File:           strings.ToLower(string(filename[0])) + filename[1:],
		SlashCommands:  []utils.CommandInfo{},
		PrefixCommands: []utils.CommandInfo{},
	}

	for _, slashCommand := range slashCommandList {
		cog.SlashCommands = append(cog.SlashCommands, slashCommand)
	}

	for _, prefixCommand := range prefixCommandList {
		cog.PrefixCommands = append(cog.PrefixCommands, prefixCommand)
	}

	cog.Env = "development"
	config.Cogs = append(config.Cogs, cog)

	jsonData, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		fmt.Println("failed to marshal config to JSON: %w", err)
		return
	}

	confDir, err := utils.FindBotConf()
	if err != nil {
		fmt.Println("Error: %w", err)
		return
	}

	confPath := filepath.Join(confDir, "botbox.conf")

	err = os.WriteFile(confPath, jsonData, 0644)
	if err != nil {
		fmt.Println("failed to write updated botbox.conf: %w", err)
		return
	}
}

func getReturnValue(returnType string) string {
	switch returnType {
	case "str":
		return `""`
	case "int":
		return "0"
	case "float":
		return "0.0"
	case "bool":
		return "False"
	default:
		return "None"
	}
}

func buildArgString(args []utils.ArgInfo) string {
	if len(args) == 0 {
		return ""
	}
	var argBuilder strings.Builder
	for i, arg := range args {
		fmt.Fprintf(&argBuilder, "%s: %s", arg.Name, arg.Type)
		if i < len(args)-1 {
			argBuilder.WriteString(", ")
		}
	}
	return argBuilder.String()
}

func init() {
	rootCmd.AddCommand(addCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// addCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	addCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}

/*
Copyright © 2025 Austin "Choice404" Choi

https://github.com/choice404/botbox

Bot Box
A discord bot template generator to help create discord bots quickly and easily

This code is licensed under the MIT License.

MIT License

Copyright (c) 2025 Austin Choi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
